 Source = Folder.Files("C:\Users\archi\OneDrive\Documents\Data_Review"),
    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"StudyID", type text}, {"SubjectID", type text}, {"Age", Int64.Type}, {"Gender", type text}, {"LabRefID", type text}, {"VisitNumber", Int64.Type}, {"VisitType", type text}, {"LabDateTime", type datetime}, {"Analyte", type text}, {"LabCategory", type text}, {"SampleType", type text}, {"LabMethod", type text}, {"LabResult", type number}, {"Unit", type text}, {"LabLLN", type number}, {"LabULN", type number}, {"LabResultIndicator", type text}, {"SeverityCategory", type text}, {"DataExportBatch", type text}, {"EDCSystemVersion", type text}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Source.Name", "SubjectID", "VisitType", "LabDateTime", "Analyte", "LabResult", "Unit", "LabLLN", "LabULN", "LabResultIndicator"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Other Columns",{"Source.Name", "SubjectID", "VisitType", "Analyte", "LabResult", "Unit", "LabLLN", "LabULN", "LabResultIndicator", "LabDateTime"}),
    LabDateTime = Table.DuplicateColumn(#"Reordered Columns", "LabDateTime", "LabDateTime - Copy"),
    #"Extracted Date" = Table.TransformColumns(LabDateTime,{{"LabDateTime", DateTime.Date, type date}}),
    #"Extracted Time" = Table.TransformColumns(#"Extracted Date",{{"LabDateTime - Copy", DateTime.Time, type time}}),
    New_LabDate = Table.RenameColumns(#"Extracted Time",{{"LabDateTime", "LabDate"}, {"LabDateTime - Copy", "LabTime"}}),
    #"Pivot Analyte by Lab Results" = Table.Pivot(New_LabDate, List.Distinct(New_LabDate[Analyte]), "Analyte", "LabResult", List.Sum),
    #"Added Conditional Column" = Table.AddColumn(#"Pivot Analyte by Lab Results", "ALT Alert", each if [ALT] > 112 then "Critical Value_Follow_Up" else "No "),
    #"Replaced Errors" = Table.ReplaceErrorValues(#"Added Conditional Column", {{"ALT Alert", "No"}}),
    #"Added Conditional Column1" = Table.AddColumn(#"Replaced Errors", "AST Alert", each if [AST] > 80 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors1" = Table.ReplaceErrorValues(#"Added Conditional Column1", {{"AST Alert", "No"}}),
    #"Added Conditional Column2" = Table.AddColumn(#"Replaced Errors1", "Bilirubin Alert", each if [Bilirubin] > 2.4 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors2" = Table.ReplaceErrorValues(#"Added Conditional Column2", {{"Bilirubin Alert", "No"}}),
    #"Added Conditional Column3" = Table.AddColumn(#"Replaced Errors2", "Creatinine Alert", each if [Creatinine] > 2 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors3" = Table.ReplaceErrorValues(#"Added Conditional Column3", {{"Creatinine Alert", "No"}}),
    #"Added Conditional Column4" = Table.AddColumn(#"Replaced Errors3", "Hemogbobin Alert", each if [Hemoglobin] < 10 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors4" = Table.ReplaceErrorValues(#"Added Conditional Column4", {{"Hemogbobin Alert", "No"}}),
    #"Added Conditional Column5" = Table.AddColumn(#"Replaced Errors4", "Sodium Alert", each if [Sodium] > 150 then "Critical Value_Follow_Up" else if [Sodium] < 130 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors5" = Table.ReplaceErrorValues(#"Added Conditional Column5", {{"Sodium Alert", "No"}}),
    #"Added Conditional Column6" = Table.AddColumn(#"Replaced Errors5", "Potassium Alert", each if [Potassium] > 5.5 then "Critical Value_Follow_Up" else if [Potassium] < 3 then "Critical Value_Follow_Up" else "No"),
    #"Replaced Errors6" = Table.ReplaceErrorValues(#"Added Conditional Column6", {{"Potassium Alert", "No"}}),
    #"Filtered Rows" = Table.SelectRows(#"Replaced Errors6", each [LabDate] >= Date.AddDays(Date.From(DateTime.LocalNow()), -8) and [LabDate] <= Date.From(DateTime.LocalNow())),
    #"Reordered Columns1" = Table.ReorderColumns(#"Filtered Rows",{"Source.Name", "SubjectID", "ALT", "AST", "Bilirubin", "Creatinine", "Hemoglobin", "Potassium", "Sodium", "Unit", "LabLLN", "LabULN", "VisitType", "LabResultIndicator", "LabDate", "LabTime", "ALT Alert", "AST Alert", "Bilirubin Alert", "Creatinine Alert", "Hemogbobin Alert", "Sodium Alert", "Potassium Alert"})
in
    #"Reordered Columns1"